CREATE TABLE IF NOT EXISTS projects (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(255) NOT NULL,
    summary           VARCHAR(500),
    description       TEXT,
    thumbnail_url     TEXT,
    feature_image_urls TEXT,
    feature_image_captions TEXT,
    project_url       VARCHAR(500),
    start_date        DATE,
    end_date          DATE,
    use_yn            CHAR(1) NOT NULL DEFAULT 'Y',
    tech_stack        TEXT,
    my_role           TEXT,
    trouble_shooting  TEXT,
    github_url        VARCHAR(500),
    deploy_url        VARCHAR(500),
    result            TEXT,
    display_order     INTEGER NOT NULL DEFAULT 0,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP
);

ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS project_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS feature_image_urls TEXT,
    ADD COLUMN IF NOT EXISTS feature_image_captions TEXT,
    ADD COLUMN IF NOT EXISTS use_yn CHAR(1) NOT NULL DEFAULT 'Y',
    ADD COLUMN IF NOT EXISTS tech_stack TEXT,
    ADD COLUMN IF NOT EXISTS my_role TEXT,
    ADD COLUMN IF NOT EXISTS trouble_shooting TEXT,
    ADD COLUMN IF NOT EXISTS github_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS deploy_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS result TEXT,
    ADD COLUMN IF NOT EXISTS display_order INTEGER NOT NULL DEFAULT 0;

ALTER TABLE projects
    ALTER COLUMN thumbnail_url TYPE TEXT;

WITH ordered_projects AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id DESC) AS sort_order
    FROM projects
    WHERE display_order = 0
)
UPDATE projects
SET display_order = ordered_projects.sort_order
FROM ordered_projects
WHERE projects.id = ordered_projects.id;

CREATE TABLE IF NOT EXISTS visits (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_url    VARCHAR(1000),
    referrer    VARCHAR(1000),
    ref_param   VARCHAR(255),
    ip_address  VARCHAR(100),
    user_agent  TEXT,
    visited_at  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT NOT NULL UNIQUE REFERENCES projects(id) ON DELETE CASCADE,
    filename     VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    file_size    BIGINT NOT NULL,
    data         BYTEA NOT NULL,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_troubles (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id            BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    title                 VARCHAR(255),
    problem               TEXT,
    selected_solution_id  BIGINT,
    selected_reason       TEXT,
    sort_order            INTEGER NOT NULL DEFAULT 0,
    created_at            TIMESTAMP,
    updated_at            TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_trouble_solutions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trouble_id  BIGINT NOT NULL REFERENCES project_troubles(id) ON DELETE CASCADE,
    title       VARCHAR(255),
    pros        TEXT,
    cons        TEXT,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_project_troubles_selected_solution'
    ) THEN
        ALTER TABLE project_troubles
            ADD CONSTRAINT fk_project_troubles_selected_solution
            FOREIGN KEY (selected_solution_id)
            REFERENCES project_trouble_solutions(id)
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_project_troubles_project_id
    ON project_troubles(project_id, sort_order, id);

CREATE INDEX IF NOT EXISTS idx_project_trouble_solutions_trouble_id
    ON project_trouble_solutions(trouble_id, sort_order, id);

CREATE TABLE IF NOT EXISTS chat_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question      TEXT NOT NULL,
    answer        TEXT,
    success_yn    CHAR(1) NOT NULL DEFAULT 'Y',
    error_message TEXT,
    created_at    TIMESTAMP
);
