CREATE TABLE IF NOT EXISTS projects (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(255) NOT NULL,
    summary           VARCHAR(500),
    description       TEXT,
    thumbnail_url     TEXT,
    feature_image_urls TEXT,
    feature_image_captions TEXT,
    project_url       VARCHAR(500),
    start_date        DATE,
    end_date          DATE,
    use_yn            CHAR(1) NOT NULL DEFAULT 'Y',
    tech_stack        TEXT,
    my_role           TEXT,
    trouble_shooting  TEXT,
    github_url        VARCHAR(500),
    deploy_url        VARCHAR(500),
    result            TEXT,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP
);

ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS project_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS feature_image_urls TEXT,
    ADD COLUMN IF NOT EXISTS feature_image_captions TEXT,
    ADD COLUMN IF NOT EXISTS use_yn CHAR(1) NOT NULL DEFAULT 'Y',
    ADD COLUMN IF NOT EXISTS tech_stack TEXT,
    ADD COLUMN IF NOT EXISTS my_role TEXT,
    ADD COLUMN IF NOT EXISTS trouble_shooting TEXT,
    ADD COLUMN IF NOT EXISTS github_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS deploy_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS result TEXT;

ALTER TABLE projects
    ALTER COLUMN thumbnail_url TYPE TEXT;
